// This file is "main.dart"
import 'dart:io';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'upload_freezed.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.

@freezed
class UploadFreezed with _$UploadFreezed {
  const factory UploadFreezed({
    File? image,
    @Default('Upload gambar terlebih dahulu') String result,
    @Default('-') String red,
    @Default('-') String green,
    @Default('-') String blue,
    required bool isUpload,
    required String selectedType,
  }) = _UploadFreezed;
}
